version: "3.7"
services:
  cryptostore:
    logging:
      driver: "json-file"
      options:
        max-size: "2000k"
        max-file: "10"
    build:
      context: .
      dockerfile: Dockerfile
  redisdb:
    logging:
      driver: "json-file"
      options:
        max-size: "2000k"
        max-file: "10"
    image: redis:5.0.5
    expose:
      - 6379
    command: ["redis-server", "--save", "''", "--appendonly", "no"]
  mongo:
    deploy:
      resources:
        limits:
          memory: 2G
    logging:
      driver: "json-file"
      options:
        max-size: "2000k"
        max-file: "10"
    container_name: mongo
    image: mongo:4.0.9-xenial
    ports:
      - '37017:27017'
    expose:
      - 27017
    command: ["mongod", "--wiredTigerCacheSizeGB", "0.25"]
