version: "3.0"
services:
  cryptostore:
    logging:
      driver: "json-file"
      options:
        max-size: "2000k"
        max-file: "10"
    image: 966108416930.dkr.ecr.us-east-1.amazonaws.com/ftx-perps:latest
  redisdb:
    logging:
      driver: "json-file"
      options:
        max-size: "2000k"
        max-file: "10"
    image: redis:5.0.5
    ports:
    - "6379:6379"
    command: ["redis-server", "--save", "''", "--appendonly", "no"]
