exchanges:
    BINANCE:
        retries: -1
        l2_book:
            symbols: [BTC-USDT, XRP-USDT, ETH-USDT, XLM-USDT, LTC-USDT, DASH-USDT, BCH-USDT, BNB-USDT, ETH-BTC, EOS-USDT, BNB-BTC, LINK-USDT, XTZ-USDT, TRX-USDT]
            book_delta: true
        trades: [BTC-USDT, XRP-USDT, ETH-USDT, XLM-USDT, LTC-USDT, DASH-USDT, BCH-USDT, BNB-USDT, ETH-BTC, EOS-USDT, BNB-BTC, LINK-USDT, XTZ-USDT, TRX-USDT]
        ticker: [BTC-USDT, XRP-USDT, ETH-USDT, XLM-USDT, LTC-USDT, DASH-USDT, BCH-USDT, BNB-USDT, ETH-BTC, EOS-USDT, BNB-BTC, LINK-USDT, XTZ-USDT, TRX-USDT]
