exchanges:
    COINBASE:
        retries: -1
        l2_book:
            symbols: [BTCUSD, ETHUSD]
            book_delta: true
        trades: [BTCUSD, ETHUSD]
        ticker: [BTCUSD, ETHUSD]
        open_interest: [BTCUSD, ETHUSD]
        funding: [BTCUSD, ETHUSD]
